### ISSUE TITLE
question on workflow

### ISSUE THREAD

**Issue by meho4990** [AlexMKramer/ComfyUIDiscordBot#1]
I'd like to squeeze additional nodes into the workflow thats used at the bottom of comfyAPI.py as "prompt_text".
Could you share the workflow its based on so modifications can be made in comfyUI and saved as a .json?

**Comment by AlexMKramer** [comment]
Here is my current workflow.  Jsons cant be linked in here, so just copy that and save as a json file.

You'll also have to format it.  I use: https://jsonformatter.org/

`{
  "last_node_id": 147,
  "last_link_id": 552,
  "nodes": [
    {
      "id": 134,
      "type": "Reroute",
      "pos": [
        805.2004028320308,
        -1248.6007812500018
      ],
      "size": [
        75,
        26
      ],
      "flags": {},
      "order": 18,
      "mode": 0,
      "inputs": [
        {
          "name": "",
          "type": "*",
          "link": 514,
          "slot_index": 0
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "VAE",
          "links": [
            515
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "showOutputText": false,
        "horizontal": false
      }
    },
    {
      "id": 8,
      "type": "VAEDecode",
      "pos": [
        920.2004028320308,
        -1218.6007812500018
      ],
      "size": {
        "0": 140,
        "1": 46
      },
      "flags": {
        "collapsed": true
      },
      "order": 24,
      "mode": 0,
      "inputs": [
        {
          "name": "samples",
          "type": "LATENT",
          "link": 56
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": 515
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            491
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "VAEDecode"
      },
      "color": "#222",
      "bgcolor": "#000"
    },
    {
      "id": 122,
      "type": "SaveImage",
      "pos": [
        790,
        -1173
      ],
      "size": {
        "0": 404.3124694824219,
        "1": 454.1047668457031
      },
      "flags": {},
      "order": 25,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 491
        }
      ],
      "title": "Refiner Output",
      "properties": {},
      "widgets_values": [
        "ComfyUI"
      ],
      "color": "#223",
      "bgcolor": "#335"
    },
    {
      "id": 141,
      "type": "Reroute",
      "pos": [
        454.93465574072343,
        -601.4836639351809
      ],
      "size": [
        75,
        26
      ],
      "flags": {},
      "order": 11,
      "mode": 0,
      "inputs": [
        {
          "name": "",
          "type": "*",
          "link": 532
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "CLIP",
          "links": [
            531,
            533
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "showOutputText": false,
        "horizontal": false
      }
    },
    {
      "id": 126,
      "type": "Reroute",
      "pos": [
        770.2418319675904,
        -622.9673278703617
      ],
      "size": [
        75,
        26
      ],
      "flags": {},
      "order": 15,
      "mode": 0,
      "inputs": [
        {
          "name": "",
          "type": "*",
          "link": 529
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "MODEL",
          "links": [
            506
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "showOutputText": false,
        "horizontal": false
      }
    },
    {
      "id": 133,
      "type": "Reroute",
      "pos": [
        770.2418319675904,
        -582.9673278703617
      ],
      "size": [
        75,
        26
      ],
      "flags": {},
      "order": 12,
      "mode": 0,
      "inputs": [
        {
          "name": "",
          "type": "*",
          "link": 513
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "VAE",
          "links": [
            514
          ]
        }
      ],
      "properties": {
        "showOutputText": false,
        "horizontal": false
      }
    },
    {
      "id": 139,
      "type": "Reroute",
      "pos": [
        434.93465574072343,
        -31.483663935180807
      ],
      "size": [
        75,
        26
      ],
      "flags": {},
      "order": 14,
      "mode": 0,
      "inputs": [
        {
          "name": "",
          "type": "*",
          "link": 524
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "CLIP",
          "links": [
            522,
            523
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "showOutputText": false,
        "horizontal": false
      }
    },
    {
      "id": 140,
      "type": "Reroute",
      "pos": [
        434.93465574072343,
        -51.483663935180815
      ],
      "size": [
        75,
        26
      ],
      "flags": {},
      "order": 13,
      "mode": 0,
      "inputs": [
        {
          "name": "",
          "type": "*",
          "link": 527
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "MODEL",
          "links": [
            535
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "showOutputText": false,
        "horizontal": false
      }
    },
    {
      "id": 5,
      "type": "EmptyLatentImage",
      "pos": [
        330,
        -1230
      ],
      "size": {
        "0": 423.9580383300781,
        "1": 106
      },
      "flags": {
        "collapsed": false
      },
      "order": 0,
      "mode": 0,
      "inputs": [],
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            49
          ],
          "slot_index": 0
        }
      ],
      "title": "Image Resolution",
      "properties": {
        "Node name for S&R": "EmptyLatentImage"
      },
      "widgets_values": [
        1024,
        1024,
        1
      ],
      "color": "#432",
      "bgcolor": "#653"
    },
    {
      "id": 115,
      "type": "PrimitiveNode",
      "pos": [
        330,
        -1080
      ],
      "size": {
        "0": 210,
        "1": 82
      },
      "flags": {
        "collapsed": false
      },
      "order": 1,
      "mode": 0,
      "outputs": [
        {
          "name": "INT",
          "type": "INT",
          "links": [
            474,
            475
          ],
          "slot_index": 0,
          "widget": {
            "name": "steps",
            "config": [
              "INT",
              {
                "default": 20,
                "min": 1,
                "max": 10000
              }
            ]
          }
        }
      ],
      "title": "Steps",
      "properties": {},
      "widgets_values": [
        20,
        "fixed"
      ],
      "color": "#233",
      "bgcolor": "#355"
    },
    {
      "id": 101,
      "type": "PrimitiveNode",
      "pos": [
        550,
        -1080
      ],
      "size": {
        "0": 210,
        "1": 82
      },
      "flags": {},
      "order": 2,
      "mode": 0,
      "outputs": [
        {
          "name": "FLOAT",
          "type": "FLOAT",
          "links": [
            380
          ],
          "slot_index": 0,
          "widget": {
            "name": "cfg",
            "config": [
              "FLOAT",
              {
                "default": 8,
                "min": 0,
                "max": 100
              }
            ]
          }
        }
      ],
      "title": "Base CFG",
      "properties": {},
      "widgets_values": [
        7.5,
        "fixed"
      ],
      "color": "#233",
      "bgcolor": "#355"
    },
    {
      "id": 66,
      "type": "PrimitiveNode",
      "pos": [
        330,
        -940
      ],
      "size": {
        "0": 210,
        "1": 82
      },
      "flags": {},
      "order": 3,
      "mode": 0,
      "outputs": [
        {
          "name": "INT",
          "type": "INT",
          "links": [
            214,
            482
          ],
          "widget": {
            "name": "noise_seed",
            "config": [
              "INT",
              {
                "default": 0,
                "min": 0,
                "max": 18446744073709552000
              }
            ]
          },
          "slot_index": 0
        }
      ],
      "title": "Seed",
      "properties": {},
      "widgets_values": [
        72,
        "increment"
      ],
      "color": "#233",
      "bgcolor": "#355"
    },
    {
      "id": 102,
      "type": "PrimitiveNode",
      "pos": [
        550,
        -940
      ],
      "size": {
        "0": 210,
        "1": 82
      },
      "flags": {},
      "order": 4,
      "mode": 0,
      "outputs": [
        {
          "name": "FLOAT",
          "type": "FLOAT",
          "links": [
            384
          ],
          "slot_index": 0,
          "widget": {
            "name": "cfg",
            "config": [
              "FLOAT",
              {
                "default": 8,
                "min": 0,
                "max": 100
              }
            ]
          }
        }
      ],
      "title": "Refiner CFG",
      "properties": {},
      "widgets_values": [
        7.5,
        "fixed"
      ],
      "color": "#233",
      "bgcolor": "#355"
    },
    {
      "id": 137,
      "type": "PrimitiveNode",
      "pos": [
        330,
        -800
      ],
      "size": {
        "0": 210,
        "1": 82
      },
      "flags": {},
      "order": 5,
      "mode": 0,
      "outputs": [
        {
          "name": "FLOAT",
          "type": "FLOAT",
          "links": [
            518
          ],
          "slot_index": 0,
          "widget": {
            "name": "ascore",
            "config": [
              "FLOAT",
              {
                "default": 6,
                "min": 0,
                "max": 1000,
                "step": 0.01
              }
            ]
          }
        }
      ],
      "title": "Positive A Score",
      "properties": {},
      "widgets_values": [
        6,
        "fixed"
      ],
      "color": "#233",
      "bgcolor": "#355"
    },
    {
      "id": 138,
      "type": "PrimitiveNode",
      "pos": [
        550,
        -800
      ],
      "size": {
        "0": 210,
        "1": 82
      },
      "flags": {
        "collapsed": false
      },
      "order": 6,
      "mode": 0,
      "outputs": [
        {
          "name": "FLOAT",
          "type": "FLOAT",
          "links": [
            534
          ],
          "slot_index": 0,
          "widget": {
            "name": "ascore",
            "config": [
              "FLOAT",
              {
                "default": 6,
                "min": 0,
                "max": 1000,
                "step": 0.01
              }
            ]
          }
        }
      ],
      "title": "Negative A Score",
      "properties": {},
      "widgets_values": [
        1,
        "fixed"
      ],
      "color": "#233",
      "bgcolor": "#355"
    },
    {
      "id": 145,
      "type": "Reroute",
      "pos": [
        767,
        -51
      ],
      "size": [
        75,
        26
      ],
      "flags": {},
      "order": 19,
      "mode": 0,
      "inputs": [
        {
          "name": "",
          "type": "*",
          "link": 535
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "MODEL",
          "links": [
            536
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "showOutputText": false,
        "horizontal": false
      }
    },
    {
      "id": 4,
      "type": "CheckpointLoaderSimple",
      "pos": [
        -305.06534425927657,
        -621.4836639351809
      ],
      "size": {
        "0": 315,
        "1": 98
      },
      "flags": {},
      "order": 7,
      "mode": 0,
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            546
          ],
          "slot_index": 0
        },
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            532
          ],
          "slot_index": 1
        },
        {
          "name": "VAE",
          "type": "VAE",
          "links": [
            513
          ],
          "slot_index": 2
        }
      ],
      "title": "Refiner Model",
      "properties": {
        "Node name for S&R": "CheckpointLoaderSimple"
      },
      "widgets_values": [
        "sd_xl_refiner_1.0_0.9vae.safetensors"
      ],
      "color": "#432",
      "bgcolor": "#653"
    },
    {
      "id": 10,
      "type": "CheckpointLoaderSimple",
      "pos": [
        -305.06534425927657,
        -51.483663935180815
      ],
      "size": {
        "0": 315,
        "1": 98
      },
      "flags": {},
      "order": 8,
      "mode": 0,
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            527
          ],
          "slot_index": 0
        },
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            524
          ],
          "slot_index": 1
        },
        {
          "name": "VAE",
          "type": "VAE",
          "links": [],
          "slot_index": 2
        }
      ],
      "title": "Base Model",
      "properties": {
        "Node name for S&R": "CheckpointLoaderSimple"
      },
      "widgets_values": [
        "sd_xl_base_1.0_0.9vae.safetensors"
      ],
      "color": "#432",
      "bgcolor": "#653"
    },
    {
      "id": 23,
      "type": "KSamplerAdvanced",
      "pos": [
        880,
        -623
      ],
      "size": {
        "0": 268.3213195800781,
        "1": 298
      },
      "flags": {
        "collapsed": false
      },
      "order": 23,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 506
        },
        {
          "name": "positive",
          "type": "CONDITIONING",
          "link": 480
        },
        {
          "name": "negative",
          "type": "CONDITIONING",
          "link": 299
        },
        {
          "name": "latent_image",
          "type": "LATENT",
          "link": 55
        },
        {
          "name": "cfg",
          "type": "FLOAT",
          "link": 384,
          "widget": {
            "name": "cfg",
            "config": [
              "FLOAT",
              {
                "default": 8,
                "min": 0,
                "max": 100
              }
            ]
          }
        },
        {
          "name": "steps",
          "type": "INT",
          "link": 475,
          "widget": {
            "name": "steps",
            "config": [
              "INT",
              {
                "default": 20,
                "min": 1,
                "max": 10000
              }
            ]
          }
        },
        {
          "name": "noise_seed",
          "type": "INT",
          "link": 482,
          "widget": {
            "name": "noise_seed",
            "config": [
              "INT",
              {
                "default": 0,
                "min": 0,
                "max": 18446744073709552000
              }
            ]
          },
          "slot_index": 6
        }
      ],
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            56
          ],
          "slot_index": 0
        }
      ],
      "title": "Second Pass Latent",
      "properties": {
        "Node name for S&R": "KSamplerAdvanced"
      },
      "widgets_values": [
        "disable",
        71,
        "fixed",
        20,
        7.5,
        "dpmpp_2m",
        "karras",
        13,
        20,
        "disable"
      ],
      "color": "#323",
      "bgcolor": "#535"
    },
    {
      "id": 22,
      "type": "KSamplerAdvanced",
      "pos": [
        880.2418319675904,
        -272.9673278703617
      ],
      "size": {
        "0": 269.9818420410156,
        "1": 298
      },
      "flags": {
        "collapsed": false
      },
      "order": 22,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 536
        },
        {
          "name": "positive",
          "type": "CONDITIONING",
          "link": 282
        },
        {
          "name": "negative",
          "type": "CONDITIONING",
          "link": 304
        },
        {
          "name": "latent_image",
          "type": "LATENT",
          "link": 49
        },
        {
          "name": "noise_seed",
          "type": "INT",
          "link": 214,
          "widget": {
            "name": "noise_seed",
            "config": [
              "INT",
              {
                "default": 0,
                "min": 0,
                "max": 18446744073709552000
              }
            ]
          }
        },
        {
          "name": "cfg",
          "type": "FLOAT",
          "link": 380,
          "widget": {
            "name": "cfg",
            "config": [
              "FLOAT",
              {
                "default": 8,
                "min": 0,
                "max": 100
              }
            ]
          }
        },
        {
          "name": "steps",
          "type": "INT",
          "link": 474,
          "widget": {
            "name": "steps",
            "config": [
              "INT",
              {
                "default": 20,
                "min": 1,
                "max": 10000
              }
            ]
          },
          "slot_index": 7
        }
      ],
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            55
          ],
          "slot_index": 0
        }
      ],
      "title": "First Pass Latent",
      "properties": {
        "Node name for S&R": "KSamplerAdvanced"
      },
      "widgets_values": [
        "enable",
        71,
        "fixed",
        20,
        7.5,
        "dpmpp_2m",
        "karras",
        0,
        13,
        "enable"
      ],
      "color": "#323",
      "bgcolor": "#535"
    },
    {
      "id": 142,
      "type": "Reroute",
      "pos": [
        455,
        -622
      ],
      "size": [
        75,
        26
      ],
      "flags": {},
      "order": 10,
      "mode": 0,
      "inputs": [
        {
          "name": "",
          "type": "*",
          "link": 546
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "MODEL",
          "links": [
            529
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "showOutputText": false,
        "horizontal": false
      }
    },
    {
      "id": 81,
      "type": "CLIPTextEncodeSDXLRefiner",
      "pos": [
        583,
        -550
      ],
      "size": {
        "0": 400,
        "1": 200
      },
      "flags": {
        "collapsed": true
      },
      "order": 16,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 531
        },
        {
          "name": "text",
          "type": "STRING",
          "link": 552,
          "widget": {
            "name": "text",
            "config": [
              "STRING",
              {
                "multiline": true
              }
            ]
          }
        },
        {
          "name": "ascore",
          "type": "FLOAT",
          "link": 534,
          "widget": {
            "name": "ascore",
            "config": [
              "FLOAT",
              {
                "default": 6,
                "min": 0,
                "max": 1000,
                "step": 0.01
              }
            ]
          }
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            299
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "title": "Negative Refiner",
      "properties": {
        "Node name for S&R": "CLIPTextEncodeSDXLRefiner"
      },
      "widgets_values": [
        1,
        4096,
        4096,
        "Deformed, unrealistic, bad quality, grainy, noisy, plastic, hazy, low contrast"
      ],
      "color": "#322",
      "bgcolor": "#533"
    },
    {
      "id": 120,
      "type": "CLIPTextEncodeSDXLRefiner",
      "pos": [
        587,
        -587
      ],
      "size": {
        "0": 400,
        "1": 200
      },
      "flags": {
        "collapsed": true
      },
      "order": 17,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 533,
          "slot_index": 0
        },
        {
          "name": "text",
          "type": "STRING",
          "link": 547,
          "widget": {
            "name": "text",
            "config": [
              "STRING",
              {
                "multiline": true
              }
            ]
          },
          "slot_index": 1
        },
        {
          "name": "ascore",
          "type": "FLOAT",
          "link": 518,
          "widget": {
            "name": "ascore",
            "config": [
              "FLOAT",
              {
                "default": 6,
                "min": 0,
                "max": 1000,
                "step": 0.01
              }
            ]
          },
          "slot_index": 2
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            480
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "title": "Positive Refiner",
      "properties": {
        "Node name for S&R": "CLIPTextEncodeSDXLRefiner"
      },
      "widgets_values": [
        6,
        4096,
        4096,
        "A cinematic photograph of a corgi sitting in a field of flowers with mountains off in the background at sunset with a cloudy sky"
      ],
      "color": "#232",
      "bgcolor": "#353"
    },
    {
      "id": 82,
      "type": "CLIPTextEncodeSDXL",
      "pos": [
        597,
        3
      ],
      "size": {
        "0": 400,
        "1": 289.9999694824219
      },
      "flags": {
        "collapsed": true
      },
      "order": 20,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 522,
          "slot_index": 0
        },
        {
          "name": "text_g",
          "type": "STRING",
          "link": 550,
          "widget": {
            "name": "text_g",
            "config": [
              "STRING",
              {
                "multiline": true,
                "default": "CLIP_G"
              }
            ]
          }
        },
        {
          "name": "text_l",
          "type": "STRING",
          "link": 551,
          "widget": {
            "name": "text_l",
            "config": [
              "STRING",
              {
                "multiline": true,
                "default": "CLIP_L"
              }
            ]
          }
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            304
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "title": "Negative Base",
      "properties": {
        "Node name for S&R": "CLIPTextEncodeSDXL"
      },
      "widgets_values": [
        4096,
        4096,
        0,
        0,
        4096,
        4096,
        "Deformed, unrealistic, bad quality, grainy, noisy, plastic, hazy, low contrast",
        "Deformed, unrealistic, bad quality, grainy, noisy, plastic, hazy, low contrast"
      ],
      "color": "#322",
      "bgcolor": "#533"
    },
    {
      "id": 75,
      "type": "CLIPTextEncodeSDXL",
      "pos": [
        601,
        -32
      ],
      "size": {
        "0": 400,
        "1": 289.9999694824219
      },
      "flags": {
        "collapsed": true
      },
      "order": 21,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 523,
          "slot_index": 0
        },
        {
          "name": "text_g",
          "type": "STRING",
          "link": 548,
          "widget": {
            "name": "text_g",
            "config": [
              "STRING",
              {
                "multiline": true,
                "default": "CLIP_G"
              }
            ]
          }
        },
        {
          "name": "text_l",
          "type": "STRING",
          "link": 549,
          "widget": {
            "name": "text_l",
            "config": [
              "STRING",
              {
                "multiline": true,
                "default": "CLIP_L"
              }
            ]
          },
          "slot_index": 2
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            282
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "title": "Positive Base",
      "properties": {
        "Node name for S&R": "CLIPTextEncodeSDXL"
      },
      "widgets_values": [
        4096,
        4096,
        0,
        0,
        4096,
        4096,
        "A cinematic photograph of a corgi sitting in a field of flowers with mountains off in the background at sunset with a cloudy sky",
        "cinematic, fujifilm, national geographic, nature, snowy mountains, flowers, colorful, overcast sky, sunset"
      ],
      "color": "#232",
      "bgcolor": "#353"
    },
    {
      "id": 147,
      "type": "SDXLPromptStyler",
      "pos": [
        -306,
        -1224
      ],
      "size": {
        "0": 602.2103881835938,
        "1": 500.6933898925781
      },
      "flags": {},
      "order": 9,
      "mode": 0,
      "outputs": [
        {
          "name": "positive_prompt_text_g",
          "type": "STRING",
          "links": [
            547,
            548,
            549
          ],
          "shape": 3,
          "slot_index": 0
        },
        {
          "name": "negative_prompt_text_g",
          "type": "STRING",
          "links": [
            550,
            551,
            552
          ],
          "shape": 3,
          "slot_index": 1
        }
      ],
      "properties": {
        "Node name for S&R": "SDXLPromptStyler"
      },
      "widgets_values": [
        "modern home",
        "",
        "ads-luxury",
        "No"
      ]
    }
  ],
  "links": [
    [
      49,
      5,
      0,
      22,
      3,
      "LATENT"
    ],
    [
      55,
      22,
      0,
      23,
      3,
      "LATENT"
    ],
    [
      56,
      23,
      0,
      8,
      0,
      "LATENT"
    ],
    [
      214,
      66,
      0,
      22,
      4,
      "INT"
    ],
    [
      282,
      75,
      0,
      22,
      1,
      "CONDITIONING"
    ],
    [
      299,
      81,
      0,
      23,
      2,
      "CONDITIONING"
    ],
    [
      304,
      82,
      0,
      22,
      2,
      "CONDITIONING"
    ],
    [
      380,
      101,
      0,
      22,
      5,
      "FLOAT"
    ],
    [
      384,
      102,
      0,
      23,
      4,
      "FLOAT"
    ],
    [
      474,
      115,
      0,
      22,
      6,
      "INT"
    ],
    [
      475,
      115,
      0,
      23,
      5,
      "INT"
    ],
    [
      480,
      120,
      0,
      23,
      1,
      "CONDITIONING"
    ],
    [
      482,
      66,
      0,
      23,
      6,
      "INT"
    ],
    [
      491,
      8,
      0,
      122,
      0,
      "IMAGE"
    ],
    [
      506,
      126,
      0,
      23,
      0,
      "MODEL"
    ],
    [
      513,
      4,
      2,
      133,
      0,
      "*"
    ],
    [
      514,
      133,
      0,
      134,
      0,
      "*"
    ],
    [
      515,
      134,
      0,
      8,
      1,
      "VAE"
    ],
    [
      518,
      137,
      0,
      120,
      2,
      "FLOAT"
    ],
    [
      522,
      139,
      0,
      82,
      0,
      "CLIP"
    ],
    [
      523,
      139,
      0,
      75,
      0,
      "CLIP"
    ],
    [
      524,
      10,
      1,
      139,
      0,
      "*"
    ],
    [
      527,
      10,
      0,
      140,
      0,
      "*"
    ],
    [
      529,
      142,
      0,
      126,
      0,
      "*"
    ],
    [
      531,
      141,
      0,
      81,
      0,
      "CLIP"
    ],
    [
      532,
      4,
      1,
      141,
      0,
      "*"
    ],
    [
      533,
      141,
      0,
      120,
      0,
      "CLIP"
    ],
    [
      534,
      138,
      0,
      81,
      2,
      "FLOAT"
    ],
    [
      535,
      140,
      0,
      145,
      0,
      "*"
    ],
    [
      536,
      145,
      0,
      22,
      0,
      "MODEL"
    ],
    [
      546,
      4,
      0,
      142,
      0,
      "*"
    ],
    [
      547,
      147,
      0,
      120,
      1,
      "STRING"
    ],
    [
      548,
      147,
      0,
      75,
      1,
      "STRING"
    ],
    [
      549,
      147,
      0,
      75,
      2,
      "STRING"
    ],
    [
      550,
      147,
      1,
      82,
      1,
      "STRING"
    ],
    [
      551,
      147,
      1,
      82,
      2,
      "STRING"
    ],
    [
      552,
      147,
      1,
      81,
      1,
      "STRING"
    ]
  ],
  "groups": [
    {
      "title": "Final Image",
      "bounding": [
        779,
        -1302,
        427,
        593
      ],
      "color": "#444"
    },
    {
      "title": "Samplers",
      "bounding": [
        760,
        -700,
        451,
        758
      ],
      "color": "#444"
    },
    {
      "title": "Models, Encoders, and LoRAs",
      "bounding": [
        -318,
        -699,
        1067,
        759
      ],
      "color": "#444"
    },
    {
      "title": "Prompting",
      "bounding": [
        -318,
        -1300,
        626,
        590
      ],
      "color": "#444"
    },
    {
      "title": "Gen Settings",
      "bounding": [
        318,
        -1301,
        451,
        592
      ],
      "color": "#444"
    }
  ],
  "config": {},
  "extra": {},
  "version": 0.4
}`

**Comment by meho4990** [comment]
Thank you, that will be plenty helpful.
